# Generated by Django 4.2.4 on 2023-08-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "FoodID",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("FoodName", models.CharField(max_length=255)),
                ("ServingSize", models.CharField(max_length=50)),
                ("Carbs", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Fat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Protein", models.DecimalField(decimal_places=2, max_digits=10)),
                ("TotalCalories", models.PositiveIntegerField()),
                ("Category", models.CharField(max_length=100)),
                ("Image", models.URLField()),
                ("Ingredients", models.TextField()),
                ("Recipe", models.TextField()),
            ],
        ),
    ]
