# Generated by Django 4.2.4 on 2023-08-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_remove_fooditem_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.PositiveIntegerField()),
                ('Ratings', models.PositiveIntegerField()),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.fooditem')),
            ],
        ),
    ]
