# Generated by Django 4.2.4 on 2023-09-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Ratings',
            field=models.FloatField(),
        ),
    ]
