# Generated by Django 4.2.4 on 2023-09-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_rating_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='UserId',
        ),
    ]
