# Generated by Django 4.2.4 on 2023-09-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_rating_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Ratings',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
