# Generated by Django 4.2.4 on 2023-09-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_alter_rating_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='Ratings',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='UserId',
        ),
    ]
