# Generated by Django 4.2.4 on 2023-09-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_remove_rating_ratings_remove_rating_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='Ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='UserId',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
