# Generated by Django 4.2.4 on 2023-09-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0009_rating_ratings_rating_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('FoodID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=255)),
                ('ServingSize', models.CharField(max_length=50)),
                ('Carbs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalCalories', models.PositiveIntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Ingredients', models.TextField()),
                ('Image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.PositiveIntegerField(default=1)),
                ('Ratings', models.PositiveIntegerField(default=0)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.fooditems')),
            ],
        ),
    ]
