# Generated by Django 4.2.4 on 2023-09-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0010_fooditems_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='FoodID',
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
