# Generated by Django 4.2.4 on 2023-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0011_remove_ratings_foodid_delete_fooditems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='Type',
            field=models.CharField(default='Dinner', max_length=30),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='Veg_NonVeg',
            field=models.CharField(default='Veg', max_length=20),
        ),
    ]
