# Generated by Django 4.2.4 on 2023-09-25 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=5000)),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('thumbnail', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
